# Generated by Django 6.0.1 on 2026-01-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên loại đơn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('requires_approval_from', models.JSONField(blank=True, default=list, help_text='JSON array: ["rector", "vice_rector", "academic_dean"]', verbose_name='Yêu cầu duyệt từ')),
                ('auto_approve', models.BooleanField(default=False, verbose_name='Tự động duyệt')),
                ('max_processing_days', models.IntegerField(default=7, verbose_name='Số ngày xử lý tối đa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loại đơn từ',
                'verbose_name_plural': 'Loại đơn từ',
                'db_table': 'petition_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('attachment_url', models.URLField(blank=True, verbose_name='File đính kèm')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp'), ('IN_REVIEW', 'Đang xét duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('processing_deadline', models.DateField(blank=True, null=True, verbose_name='Hạn xử lý')),
                ('final_decision', models.TextField(blank=True, verbose_name='Quyết định cuối cùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions', to=settings.AUTH_USER_MODEL, verbose_name='Người nộp đơn')),
                ('petition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petitions', to='petitions.petitiontype', verbose_name='Loại đơn')),
            ],
            options={
                'verbose_name': 'Đơn từ',
                'verbose_name_plural': 'Đơn từ',
                'db_table': 'petitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Đã nộp'), ('REVIEWED', 'Đã xem'), ('COMMENTED', 'Nhận xét'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('REQUESTED_CHANGES', 'Yêu cầu sửa')], max_length=30, verbose_name='Hành động')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petition_actions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='petitions.petition', verbose_name='Đơn từ')),
            ],
            options={
                'verbose_name': 'Lịch sử đơn từ',
                'verbose_name_plural': 'Lịch sử đơn từ',
                'db_table': 'petition_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['petitioner', 'status'], name='petitions_petitio_1efe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['status', 'submitted_at'], name='petitions_status_3bcfcf_idx'),
        ),
    ]
