# Generated by Django 6.0.1 on 2026-01-17 14:04

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='content',
        ),
        migrations.RemoveField(
            model_name='petitionhistory',
            name='comment',
        ),
        migrations.AddField(
            model_name='petition',
            name='admin_response',
            field=models.TextField(blank=True, verbose_name='Phản hồi của Ban Giám hiệu'),
        ),
        migrations.AddField(
            model_name='petition',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='petitions/attachments/', verbose_name='Tệp đính kèm (upload)'),
        ),
        migrations.AddField(
            model_name='petition',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do / Nội dung'),
        ),
        migrations.AddField(
            model_name='petitionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petitionhistory',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú / Nhận xét'),
        ),
        migrations.AddField(
            model_name='petitionhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='petitiontype',
            name='code',
            field=models.CharField(default='DEFAULT', help_text='Ví dụ: LEAVE, DEFER, TRANSCRIPT', max_length=50, unique=True, verbose_name='Mã loại đơn'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='attachment_url',
            field=models.URLField(blank=True, verbose_name='File đính kèm (URL)'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp'), ('IN_REVIEW', 'Đang xét duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='petitionhistory',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Đã nộp'), ('VIEWED', 'Đã xem'), ('REVIEWED', 'Đã xem xét'), ('COMMENTED', 'Nhận xét'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('REQUESTED_CHANGES', 'Yêu cầu sửa'), ('CANCELLED', 'Đã hủy')], max_length=50, verbose_name='Hành động'),
        ),
        migrations.AlterField(
            model_name='petitionhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên loại đơn'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='requires_approval_from',
            field=models.JSONField(blank=True, default=list, help_text='JSON array: ["abbot", "teacher", "admission"]', verbose_name='Yêu cầu duyệt từ'),
        ),
        migrations.AlterField(
            model_name='petitiontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddIndex(
            model_name='petition',
            index=models.Index(fields=['petition_type'], name='petitions_petitio_0e542e_idx'),
        ),
        migrations.AddIndex(
            model_name='petitionhistory',
            index=models.Index(fields=['petition', 'action'], name='petition_hi_petitio_3eda60_idx'),
        ),
        migrations.AddIndex(
            model_name='petitionhistory',
            index=models.Index(fields=['actor'], name='petition_hi_actor_i_7a30ac_idx'),
        ),
        migrations.AddIndex(
            model_name='petitiontype',
            index=models.Index(fields=['code'], name='petition_ty_code_bfd959_idx'),
        ),
        migrations.AddIndex(
            model_name='petitiontype',
            index=models.Index(fields=['is_active'], name='petition_ty_is_acti_325163_idx'),
        ),
    ]
