# Generated by Django 6.0.1 on 2026-01-09 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('monk', 'Tăng sinh'), ('layperson', 'Cư sĩ')], default='layperson', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('abbot', 'Hòa thượng'), ('teacher', 'Giáo thọ'), ('student', 'Sinh viên'), ('admission', 'Ban tuyển sinh'), ('content', 'Biên tập viên'), ('secretary', 'Thư ký')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(default='km', max_length=10)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LaypersonProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True)),
                ('nationality', models.CharField(default='Việt Nam', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.JSONField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('buddhist_name', models.CharField(blank=True, max_length=100)),
                ('refuge_date', models.DateField(blank=True, null=True)),
                ('refuge_temple', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.URLField(blank=True)),
                ('id_card_url', models.URLField(blank=True)),
                ('student_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cohort', models.CharField(blank=True, max_length=20)),
                ('current_year', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('on_leave', 'Tạm nghỉ'), ('graduated', 'Tốt nghiệp'), ('withdrawn', 'Nghỉ học')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layperson_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ Cư sĩ',
                'verbose_name_plural': 'Hồ sơ Cư sĩ',
                'db_table': 'layperson_profiles',
            },
        ),
        migrations.CreateModel(
            name='MonkProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dharma_name_khmer', models.CharField(max_length=100)),
                ('dharma_name_pali', models.CharField(blank=True, max_length=100)),
                ('dharma_name_vietnamese', models.CharField(blank=True, max_length=100)),
                ('secular_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.JSONField(blank=True, null=True)),
                ('nationality', models.CharField(default='Việt Nam', max_length=50)),
                ('ethnicity', models.CharField(default='Khmer', max_length=50)),
                ('ordination_temple', models.CharField(max_length=200)),
                ('ordination_temple_address', models.TextField(blank=True)),
                ('samanera_date', models.DateField(blank=True, null=True)),
                ('bhikkhu_date', models.DateField(blank=True, null=True)),
                ('upajjhaya', models.CharField(blank=True, max_length=100)),
                ('kammavacacariya', models.CharField(blank=True, max_length=100)),
                ('anusavanaccariya', models.CharField(blank=True, max_length=100)),
                ('vassa_count', models.IntegerField(default=0)),
                ('vassa_updated_at', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('ordination_certificate_url', models.URLField(blank=True)),
                ('id_card_url', models.URLField(blank=True)),
                ('secular_education', models.JSONField(blank=True, null=True)),
                ('student_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cohort', models.CharField(blank=True, max_length=20)),
                ('current_year', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('on_leave', 'Tạm nghỉ'), ('graduated', 'Tốt nghiệp'), ('disrobed', 'Hoàn tục'), ('transferred', 'Chuyển trường'), ('deceased', 'Viên tịch')], default='active', max_length=30)),
                ('status_reason', models.TextField(blank=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ Tăng sinh',
                'verbose_name_plural': 'Hồ sơ Tăng sinh',
                'db_table': 'monk_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='laypersonprofile',
            index=models.Index(fields=['full_name'], name='layperson_p_full_na_8c6263_idx'),
        ),
        migrations.AddIndex(
            model_name='laypersonprofile',
            index=models.Index(fields=['status'], name='layperson_p_status_158669_idx'),
        ),
        migrations.AddIndex(
            model_name='laypersonprofile',
            index=models.Index(fields=['student_code'], name='layperson_p_student_599449_idx'),
        ),
        migrations.AddIndex(
            model_name='monkprofile',
            index=models.Index(fields=['dharma_name_khmer'], name='monk_profil_dharma__551571_idx'),
        ),
        migrations.AddIndex(
            model_name='monkprofile',
            index=models.Index(fields=['vassa_count'], name='monk_profil_vassa_c_9a66b1_idx'),
        ),
        migrations.AddIndex(
            model_name='monkprofile',
            index=models.Index(fields=['status'], name='monk_profil_status_ab74b8_idx'),
        ),
        migrations.AddIndex(
            model_name='monkprofile',
            index=models.Index(fields=['student_code'], name='monk_profil_student_8da732_idx'),
        ),
    ]
