# Generated by Django 6.0.1 on 2026-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laypersonprofile',
            name='id_card_url',
            field=models.ImageField(blank=True, null=True, upload_to='laypeople/ids/', verbose_name='CMND/CCCD'),
        ),
        migrations.AlterField(
            model_name='laypersonprofile',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='laypeople/photos/', verbose_name='Ảnh chân dung'),
        ),
        migrations.AlterField(
            model_name='monkprofile',
            name='id_card_url',
            field=models.ImageField(blank=True, null=True, upload_to='monks/ids/', verbose_name='CMND/CCCD'),
        ),
        migrations.AlterField(
            model_name='monkprofile',
            name='ordination_certificate_url',
            field=models.ImageField(blank=True, null=True, upload_to='monks/certs/', verbose_name='Chứng điệp thọ giới'),
        ),
        migrations.AlterField(
            model_name='monkprofile',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='monks/photos/', verbose_name='Ảnh chân dung'),
        ),
    ]
