# Generated by Django 6.0.1 on 2026-01-09 16:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.CharField(max_length=20, unique=True, verbose_name='Mã năm học')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Năm học hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Năm học',
                'verbose_name_plural': 'Năm học',
                'db_table': 'academic_years',
                'ordering': ['-year_code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('name_vi', models.CharField(max_length=200, verbose_name='Tên tiếng Việt')),
                ('name_pali', models.CharField(blank=True, max_length=200, verbose_name='Tên Pali')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số tín chỉ')),
                ('level', models.CharField(choices=[('FOUNDATIONAL', 'Cơ bản'), ('INTERMEDIATE', 'Trung cấp'), ('ADVANCED', 'Nâng cao')], max_length=20, verbose_name='Cấp độ')),
                ('category', models.CharField(choices=[('VINAYA', 'Giới luật'), ('ABHIDHAMMA', 'Vi Diệu Pháp'), ('SUTTA', 'Kinh tạng'), ('PALI_LANGUAGE', 'Tiếng Pali'), ('BUDDHIST_HISTORY', 'Lịch sử Phật giáo'), ('PRACTICE', 'Thực hành'), ('OTHER', 'Khác')], max_length=30, verbose_name='Loại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'db_table': 'courses',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=50, verbose_name='Mã lớp')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng học')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='JSON: {day_of_week, start_time, end_time}', verbose_name='Lịch học')),
                ('max_students', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sĩ số tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.course', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'classes',
                'ordering': ['-semester', 'course'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('status', models.CharField(choices=[('ENROLLED', 'Đang học'), ('COMPLETED', 'Hoàn thành'), ('DROPPED', 'Đã bỏ'), ('FAILED', 'Không đạt')], default='ENROLLED', max_length=20, verbose_name='Trạng thái')),
                ('drop_date', models.DateField(blank=True, null=True, verbose_name='Ngày bỏ học')),
                ('drop_reason', models.TextField(blank=True, verbose_name='Lý do bỏ học')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.class', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Đăng ký học',
                'verbose_name_plural': 'Đăng ký học',
                'db_table': 'enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Giữa kỳ'), ('FINAL', 'Cuối kỳ'), ('MAKEUP', 'Thi lại')], max_length=20, verbose_name='Loại thi')),
                ('exam_date', models.DateField(verbose_name='Ngày thi')),
                ('exam_time', models.TimeField(verbose_name='Giờ thi')),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Thời lượng (phút)')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Phòng thi')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='academic.class', verbose_name='Lớp học')),
            ],
            options={
                'verbose_name': 'Lịch thi',
                'verbose_name_plural': 'Lịch thi',
                'db_table': 'exam_schedules',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Điểm giữa kỳ')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Điểm cuối kỳ')),
                ('attendance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tỷ lệ tham dự (%)')),
                ('grade_letter', models.CharField(blank=True, choices=[('A', 'A (4.0)'), ('B+', 'B+ (3.5)'), ('B', 'B (3.0)'), ('C+', 'C+ (2.5)'), ('C', 'C (2.0)'), ('D', 'D (1.0)'), ('F', 'F (0.0)')], max_length=2, verbose_name='Xếp loại')),
                ('gpa_points', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('4'))], verbose_name='Điểm GPA')),
                ('comments', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academic.enrollment', verbose_name='Đăng ký học')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Điểm số',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Học kỳ số')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicyear', verbose_name='Năm học')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
                'db_table': 'semesters',
                'ordering': ['-academic_year', 'semester_number'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.semester', verbose_name='Học kỳ'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='enrollments_student_929bef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'class_instance')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_code', 'semester')},
        ),
    ]
