# Generated by Django 6.0.1 on 2026-01-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='knowledge_block',
            field=models.CharField(choices=[('VINAYA', 'Giới luật'), ('ABHIDHAMMA', 'Vi Diệu Pháp'), ('SUTTA', 'Kinh tạng'), ('PALI_LANGUAGE', 'Tiếng Pali'), ('BUDDHIST_HISTORY', 'Lịch sử Phật giáo'), ('PRACTICE', 'Thực hành'), ('GENERAL_EDUCATION', 'Giáo dục đại cương'), ('OTHER', 'Khác')], default='OTHER', max_length=30, verbose_name='Khối kiến thức'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('REQUIRED', 'Bắt buộc'), ('ELECTIVE', 'Tự chọn'), ('GENERAL', 'Đại cương'), ('SPECIALIZED', 'Chuyên ngành')], default='REQUIRED', max_length=30, verbose_name='Loại'),
        ),
    ]
