# Generated by Django 6.0.1 on 2026-01-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_course_knowledge_block_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='academic.course', verbose_name='Môn tiên quyết'),
        ),
    ]
