# Generated by Django 6.0.1 on 2026-01-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_km',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Tên tiếng Khmer'),
        ),
    ]
