# Generated by Django 6.0.1 on 2026-01-15 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_course_name_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='study_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Năm học (CTĐT)'),
        ),
    ]
