# Generated by Django 6.0.1 on 2026-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='course_count',
            field=models.CharField(default='30+', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founded_year',
            field=models.CharField(default='2006', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='student_count',
            field=models.CharField(default='150+', max_length=20),
        ),
    ]
