# Generated by Django 6.0.1 on 2026-01-14 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_is_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Hoặc dán link ảnh từ nguồn bên ngoài', verbose_name='URL Thumbnail (tuỳ chọn)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(verbose_name='URL Hình ảnh (Desktop)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url_mobile',
            field=models.URLField(blank=True, verbose_name='URL Hình ảnh (Mobile)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_target',
            field=models.CharField(default='_self', max_length=20, verbose_name='Cách mở tab'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='Đường dẫn khi click'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_km',
            field=models.CharField(blank=True, max_length=300, verbose_name='Phụ đề (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle_vi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Phụ đề (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_km',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title_vi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã khoa'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_km',
            field=models.TextField(blank=True, verbose_name='Mô tả (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description_vi',
            field=models.TextField(blank=True, verbose_name='Mô tả (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng khoa'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL Ảnh'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_km',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên Khoa (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_vi',
            field=models.CharField(max_length=200, verbose_name='Tên Khoa (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon (Class)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('main_nav', 'Menu chính'), ('footer_1', 'Footer cột 1'), ('footer_2', 'Footer cột 2'), ('mobile_nav', 'Menu mobile')], max_length=50, verbose_name='Vị trí Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menu', verbose_name='Menu cha'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(default='_self', max_length=20, verbose_name='Cách mở tab'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_km',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên Menu (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title_vi',
            field=models.CharField(max_length=100, verbose_name='Tên Menu (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('academy_news', 'Tin Học viện'), ('buddhist_news', 'Phật sự cộng đồng'), ('khmer_festival', 'Lễ hội Khmer'), ('announcement', 'Thông báo'), ('event', 'Sự kiện')], default='academy_news', max_length=50, verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_km',
            field=models.TextField(blank=True, verbose_name='Nội dung (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_vi',
            field=models.TextField(verbose_name='Nội dung (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt_km',
            field=models.TextField(blank=True, verbose_name='Tóm tắt (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt_vi',
            field=models.TextField(blank=True, verbose_name='Tóm tắt (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image_url',
            field=models.ImageField(blank=True, default='', help_text='Upload ảnh trực tiếp (khuyến nghị)', null=True, upload_to='news/images/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='news',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True, verbose_name='Thư viện ảnh'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_announcement',
            field=models.BooleanField(default=False, help_text='Đánh dấu là thông báo urgent hiển thị riêng trên trang chủ', verbose_name='Thông báo quan trọng'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim lên đầu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất bản'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug (Đường dẫn)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_km',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_vi',
            field=models.CharField(max_length=300, verbose_name='Tiêu đề (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_km',
            field=models.TextField(blank=True, verbose_name='Nội dung (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_vi',
            field=models.TextField(verbose_name='Nội dung (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='excerpt_km',
            field=models.TextField(blank=True, verbose_name='Tóm tắt (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='excerpt_vi',
            field=models.TextField(blank=True, verbose_name='Tóm tắt (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='featured_image_url',
            field=models.URLField(blank=True, verbose_name='URL Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='page',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True, verbose_name='Thư viện ảnh'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự Menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'Giới thiệu'), ('history', 'Lịch sử'), ('mission', 'Sứ mệnh'), ('organization', 'Cơ cấu tổ chức'), ('facilities', 'Cơ sở vật chất'), ('curriculum', 'Chương trình đào tạo'), ('admission', 'Tuyển sinh'), ('contact', 'Liên hệ'), ('custom', 'Trang tùy chỉnh')], max_length=50, verbose_name='Loại trang'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.page', verbose_name='Trang cha'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xuất bản'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Hiển thị trên Menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug (Đường dẫn)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('archived', 'Lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='default', max_length=50, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_km',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tiêu đề (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title_vi',
            field=models.CharField(max_length=300, verbose_name='Tiêu đề (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email liên hệ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='course_count',
            field=models.CharField(default='8', max_length=20, verbose_name='Số tỉnh thành đào tạo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon_url',
            field=models.URLField(blank=True, verbose_name='URL Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text_km',
            field=models.TextField(blank=True, verbose_name='Nội dung Footer (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text_vi',
            field=models.TextField(blank=True, verbose_name='Nội dung Footer (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='founded_year',
            field=models.CharField(default='2006', max_length=20, verbose_name='Năm thành lập'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_maps_embed',
            field=models.TextField(blank=True, verbose_name='Mã nhúng Google Maps'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL Logo'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name_km',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên Website (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name_vi',
            field=models.CharField(max_length=200, verbose_name='Tên Website (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_slogan_km',
            field=models.CharField(blank=True, max_length=300, verbose_name='Khẩu hiệu (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_slogan_vi',
            field=models.CharField(blank=True, max_length=300, verbose_name='Khẩu hiệu (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='student_count',
            field=models.CharField(default='300+', max_length=20, verbose_name='Số Tăng sinh tốt nghiệp'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='URL Youtube'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='bio_km',
            field=models.TextField(blank=True, verbose_name='Tiểu sử (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='bio_vi',
            field=models.TextField(blank=True, verbose_name='Tiểu sử (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='cms.department', verbose_name='Khoa / Phòng ban'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='display_name_km',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên hiển thị (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='display_name_vi',
            field=models.CharField(max_length=200, verbose_name='Tên hiển thị (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='URL Ảnh'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_type',
            field=models.CharField(choices=[('leadership', 'Ban Giám hiệu'), ('faculty', 'Giáo thọ'), ('admin_staff', 'Nhân viên'), ('advisory', 'Cố vấn')], default='faculty', max_length=50, verbose_name='Loại nhân sự'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='title_km',
            field=models.CharField(blank=True, max_length=100, verbose_name='Học hàm/Học vị (Tiếng Khmer)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='title_vi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Học hàm/Học vị (Tiếng Việt)'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản hệ thống'),
        ),
    ]
