# Generated by Django 6.0.1 on 2026-01-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_news_thumbnail_url_alter_banner_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.ImageField(help_text='Kích thước đề xuất: 1920x600px', upload_to='banners/images/', verbose_name='Hình ảnh (Desktop)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url_mobile',
            field=models.ImageField(blank=True, help_text='Kích thước đề xuất: 800x600px', null=True, upload_to='banners/mobile/', verbose_name='Hình ảnh (Mobile)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='departments/images/', verbose_name='Ảnh đại diện Khoa'),
        ),
        migrations.AlterField(
            model_name='page',
            name='featured_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='pages/images/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/', verbose_name='Ảnh chân dung'),
        ),
    ]
