# Generated by Django 6.0.1 on 2026-01-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_banner_image_url_alter_banner_image_url_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo Đối tác'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon_url',
            field=models.ImageField(blank=True, null=True, upload_to='site/favicons/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='Logo Website'),
        ),
    ]
