# Generated by Django 6.0.1 on 2026-01-14 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_partner_logo_url_alter_sitesetting_favicon_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=20, verbose_name='Năm (Ví dụ: 2006)')),
                ('title_vi', models.CharField(max_length=200, verbose_name='Tiêu đề (Tiếng Việt)')),
                ('title_km', models.CharField(blank=True, max_length=200, verbose_name='Tiêu đề (Tiếng Khmer)')),
                ('description_vi', models.TextField(verbose_name='Mô tả (Tiếng Việt)')),
                ('description_km', models.TextField(blank=True, verbose_name='Mô tả (Tiếng Khmer)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/images/', verbose_name='Ảnh minh họa')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mốc lịch sử',
                'verbose_name_plural': 'Mốc lịch sử',
                'db_table': 'history_milestones',
                'ordering': ['display_order', 'year'],
            },
        ),
    ]
