# Generated by Django 6.0.1 on 2026-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_historymilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Ảnh lớn hiển thị đầu trang chủ.', null=True, upload_to='settings/hero/', verbose_name='Ảnh nền trang chủ (Desktop)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='settings/hero/mobile/', verbose_name='Ảnh nền trang chủ (Mobile)'),
        ),
    ]
