# Generated by Django 6.0.1 on 2026-01-10 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=255, verbose_name='Tên loại đơn')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã loại đơn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Loại đơn từ',
                'verbose_name_plural': 'Các loại đơn từ',
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('reason', models.TextField(verbose_name='Lý do')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requests/attachments/', verbose_name='Tệp đính kèm')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('REVIEWING', 'Đang xem xét'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Phản hồi của GV')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approvals.requesttype', verbose_name='Loại đơn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Đơn từ sinh viên',
                'verbose_name_plural': 'Danh sách đơn từ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('action', models.CharField(max_length=50, verbose_name='Hành động')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approvals.studentrequest')),
            ],
            options={
                'verbose_name': 'Lịch sử duyệt',
                'verbose_name_plural': 'Lịch sử duyệt',
            },
        ),
    ]
