# Generated by Django 6.0.1 on 2026-01-09 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhmerCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gregorian_date', models.DateField(unique=True, verbose_name='Ngày dương lịch')),
                ('khmer_day', models.CharField(max_length=50, verbose_name='Ngày Khmer')),
                ('khmer_month', models.CharField(choices=[('MITONA', 'មិថុនា (Tháng 6)'), ('ASADHA', 'អាសាឍ (Tháng 7)'), ('SRAVANA', 'ស្រាពណ៍ (Tháng 8)'), ('BHADRAPADA', 'ភទ្រប្រទា (Tháng 9)'), ('ASVINA', 'អស្សុជ (Tháng 10)'), ('KARTIKA', 'កត្តិក (Tháng 11)'), ('MARGASIRA', 'មិគសុិរ (Tháng 12)'), ('PAUSHA', 'បុស្ស (Tháng 1)'), ('MAGHA', 'មាឃ (Tháng 2)'), ('PHALGUNA', 'ផល្គុន (Tháng 3)'), ('CAITRA', 'ចេត្រ (Tháng 4)'), ('VAISAKHA', 'វិសាខ (Tháng 5)')], max_length=20, verbose_name='Tháng Khmer')),
                ('lunar_phase', models.CharField(blank=True, max_length=20, verbose_name='Pha trăng')),
                ('is_uposatha_day', models.BooleanField(default=False, verbose_name='Ngày trai giới')),
                ('is_pchum_ben', models.BooleanField(default=False, verbose_name='Lễ Pchum Ben')),
                ('is_chol_vossa', models.BooleanField(default=False, verbose_name='Lễ Chol Vossa (Nhập hạ)')),
                ('is_chroat_preah_vossa', models.BooleanField(default=False, verbose_name='Lễ Chroat Preah Vossa (Xuất hạ)')),
                ('is_kathina', models.BooleanField(default=False, verbose_name='Lễ Kathina (Dâng y)')),
                ('is_meak_bochea', models.BooleanField(default=False, verbose_name='Lễ Meak Bochea')),
                ('is_visak_bochea', models.BooleanField(default=False, verbose_name='Lễ Visak Bochea (Phật đản)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lịch Khmer',
                'verbose_name_plural': 'Lịch Khmer',
                'db_table': 'khmer_calendar',
                'ordering': ['gregorian_date'],
                'indexes': [models.Index(fields=['gregorian_date'], name='khmer_calen_gregori_9bc11f_idx'), models.Index(fields=['is_uposatha_day'], name='khmer_calen_is_upos_a100e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tiêu đề')),
                ('event_type', models.CharField(choices=[('CEREMONY', 'Lễ hội / Nghi lễ'), ('CLASS', 'Lớp học'), ('EXAM', 'Thi cử'), ('MEETING', 'Họp'), ('HOLIDAY', 'Ngày nghỉ'), ('VASSA', 'Hạ'), ('OTHER', 'Khác')], max_length=20, verbose_name='Loại sự kiện')),
                ('start_datetime', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_datetime', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Địa điểm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_khmer_calendar', models.BooleanField(default=False, verbose_name='Theo lịch Khmer')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Người tổ chức')),
                ('participants', models.ManyToManyField(blank=True, related_name='attending_events', to=settings.AUTH_USER_MODEL, verbose_name='Người tham gia')),
                ('khmer_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.khmercalendar', verbose_name='Ngày lịch Khmer')),
            ],
            options={
                'verbose_name': 'Sự kiện',
                'verbose_name_plural': 'Sự kiện',
                'db_table': 'events',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='events_start_d_c4a32d_idx'), models.Index(fields=['event_type'], name='events_event_t_c9f56c_idx')],
            },
        ),
    ]
