# Generated by Django 6.0.1 on 2026-01-09 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_year', models.CharField(max_length=20, verbose_name='Năm học')),
                ('application_start_date', models.DateField(verbose_name='Ngày bắt đầu nhận hồ sơ')),
                ('application_end_date', models.DateField(verbose_name='Ngày kết thúc nhận hồ sơ')),
                ('result_announcement_date', models.DateField(blank=True, null=True, verbose_name='Ngày công bố kết quả')),
                ('status', models.CharField(choices=[('UPCOMING', 'Sắp mở'), ('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng'), ('COMPLETED', 'Hoàn thành')], default='UPCOMING', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đợt tuyển sinh',
                'verbose_name_plural': 'Đợt tuyển sinh',
                'db_table': 'admission_periods',
                'ordering': ['-admission_year'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('place_of_birth', models.CharField(max_length=200, verbose_name='Nơi sinh')),
                ('current_residence', models.TextField(verbose_name='Nơi ở hiện tại')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_ordained', models.BooleanField(default=False, verbose_name='Đã xuất gia')),
                ('monk_name', models.CharField(blank=True, max_length=200, verbose_name='Pháp danh')),
                ('ordination_date', models.DateField(blank=True, null=True, verbose_name='Ngày xuất gia')),
                ('vassa_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tuổi hạ')),
                ('home_temple', models.CharField(blank=True, max_length=200, verbose_name='Chùa quản lý')),
                ('recommending_monk', models.CharField(blank=True, max_length=200, verbose_name='Sư giới thiệu')),
                ('documents', models.JSONField(blank=True, default=dict, help_text='JSON: {birth_cert_url, monk_cert_url, recommendation_letter_url}', verbose_name='Tài liệu đính kèm')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã nộp'), ('REVIEWING', 'Đang xét duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian duyệt')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('admission_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.admissionperiod', verbose_name='Đợt tuyển sinh')),
            ],
            options={
                'verbose_name': 'Đơn nhập học',
                'verbose_name_plural': 'Đơn nhập học',
                'db_table': 'admission_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='admission_a_status_ab03e4_idx'), models.Index(fields=['admission_period', 'status'], name='admission_a_admissi_9ffb27_idx')],
            },
        ),
    ]
